fill in timesync functionality
for some reason it seems like the server's clock is running slow.  it might have to do with the vm.  I've seen the vm clock fall off target before.  ping is marvelous of course, (2-3ms from my browser to the vm :D probably mostly measurement error) but I can't expect an environment like this when people are using it.  I will enforce some netem policy from now on.  not sure what settings I'll decide are my minimum target.

also, I got an error I'm not quite sure about in proxy, which has happened once before long ago:
/home/pimlu/Documents/jbogame/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: socket hang up
    at createHangUpError (http.js:1476:15)
    at Socket.socketCloseListener (http.js:1526:23)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:465:12)

I'll fix this soon.